version: '2'
services:
 angular-compose1:
    build: docker-angular
    networks:
       - test
    ports:
       - 4200:4200

 angular-compose2:
    build: docker-angular1
    networks:
       - test
    ports:
       - 4201:4200
       
 backend:
    build: backend
    networks:
     - test
    ports:
     - 8080:8080
networks: 
    test:

